/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DividedDifferenceRouteImport } from './routes/divided-difference'
import { Route as NewtonBackwardRouteImport } from './routes/newton-backward'
import { Route as NewtonForwardRouteImport } from './routes/newton-forward'
import { Route as PeakAnalysisRouteImport } from './routes/peak-analysis'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SimulationRouteImport } from './routes/simulation'
import { Route as UploadRouteImport } from './routes/upload'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DividedDifferenceRoute = DividedDifferenceRouteImport.update({
  id: '/divided-difference',
  path: '/divided-difference',
  getParentRoute: () => rootRouteImport,
} as any)
const NewtonBackwardRoute = NewtonBackwardRouteImport.update({
  id: '/newton-backward',
  path: '/newton-backward',
  getParentRoute: () => rootRouteImport,
} as any)
const NewtonForwardRoute = NewtonForwardRouteImport.update({
  id: '/newton-forward',
  path: '/newton-forward',
  getParentRoute: () => rootRouteImport,
} as any)
const PeakAnalysisRoute = PeakAnalysisRouteImport.update({
  id: '/peak-analysis',
  path: '/peak-analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SimulationRoute = SimulationRouteImport.update({
  id: '/simulation',
  path: '/simulation',
  getParentRoute: () => rootRouteImport,
} as any)
const UploadRoute = UploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/divided-difference': typeof DividedDifferenceRoute
  '/newton-backward': typeof NewtonBackwardRoute
  '/newton-forward': typeof NewtonForwardRoute
  '/peak-analysis': typeof PeakAnalysisRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/simulation': typeof SimulationRoute
  '/upload': typeof UploadRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/divided-difference': typeof DividedDifferenceRoute
  '/newton-backward': typeof NewtonBackwardRoute
  '/newton-forward': typeof NewtonForwardRoute
  '/peak-analysis': typeof PeakAnalysisRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/simulation': typeof SimulationRoute
  '/upload': typeof UploadRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/divided-difference': typeof DividedDifferenceRoute
  '/newton-backward': typeof NewtonBackwardRoute
  '/newton-forward': typeof NewtonForwardRoute
  '/peak-analysis': typeof PeakAnalysisRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/simulation': typeof SimulationRoute
  '/upload': typeof UploadRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/divided-difference'
    | '/newton-backward'
    | '/newton-forward'
    | '/peak-analysis'
    | '/reports'
    | '/settings'
    | '/simulation'
    | '/upload'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/divided-difference'
    | '/newton-backward'
    | '/newton-forward'
    | '/peak-analysis'
    | '/reports'
    | '/settings'
    | '/simulation'
    | '/upload'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/divided-difference'
    | '/newton-backward'
    | '/newton-forward'
    | '/peak-analysis'
    | '/reports'
    | '/settings'
    | '/simulation'
    | '/upload'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  DividedDifferenceRoute: typeof DividedDifferenceRoute
  NewtonBackwardRoute: typeof NewtonBackwardRoute
  NewtonForwardRoute: typeof NewtonForwardRoute
  PeakAnalysisRoute: typeof PeakAnalysisRoute
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
  SimulationRoute: typeof SimulationRoute
  UploadRoute: typeof UploadRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/divided-difference': {
      id: '/divided-difference'
      path: '/divided-difference'
      fullPath: '/divided-difference'
      preLoaderRoute: typeof DividedDifferenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/newton-backward': {
      id: '/newton-backward'
      path: '/newton-backward'
      fullPath: '/newton-backward'
      preLoaderRoute: typeof NewtonBackwardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/newton-forward': {
      id: '/newton-forward'
      path: '/newton-forward'
      fullPath: '/newton-forward'
      preLoaderRoute: typeof NewtonForwardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/peak-analysis': {
      id: '/peak-analysis'
      path: '/peak-analysis'
      fullPath: '/peak-analysis'
      preLoaderRoute: typeof PeakAnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulation': {
      id: '/simulation'
      path: '/simulation'
      fullPath: '/simulation'
      preLoaderRoute: typeof SimulationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  DividedDifferenceRoute: DividedDifferenceRoute,
  NewtonBackwardRoute: NewtonBackwardRoute,
  NewtonForwardRoute: NewtonForwardRoute,
  PeakAnalysisRoute: PeakAnalysisRoute,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
  SimulationRoute: SimulationRoute,
  UploadRoute: UploadRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
